# Generated by Django 5.2.17 on 2026-09-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('mileage', models.FloatField()),
                ('horsepower', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(default='Unknown', max_length=20)),
                ('transmission', models.CharField(max_length=15)),
                ('drivetrain', models.CharField(default='unknown', max_length=10)),
                ('body_style', models.CharField(default='unknown', max_length=15)),
                ('fuel', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
