# Generated by Django 5.1.1 on 2024-09-26 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.FloatField()),
                ('horsepower', models.IntegerField(db_column='hp')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.IntegerField()),
                ('conditon', models.CharField(db_column='offerType', max_length=20)),
                ('transmission', models.CharField(db_column='gear', max_length=15)),
                ('fuel', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=30)),
                ('make', models.CharField(max_length=30)),
            ],
        ),
    ]
